environment:
  APPVEYOR_RDP_PASSWORD: MagicPass

before_build:
  - set
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))  
