environment:
  APPVEYOR_RDP_PASSWORD: MagicPass@1024

before_build:
  - start cmd /K set
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))  
